apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: "cert-manager"
  name: "letsencrypt-prod"
spec:
  acme:
    # To use the staging environment, use the following line:
    # server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    # To use the production environment, use the following line instead:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "onyekagodonu@yahoo.com"
    privateKeySecretRef:
      name: "letsencrypt-prod"
    solvers:
    - selector:
        dnsZones:
          - "onyeka.ga"
      dns01:
        route53:
          region: "us-east-2"
          hostedZoneID: "Z04691211KDDO99P3LFH7"